openapi: 3.0.0
info:
  title: Caesar Cipher Service
  version: 1.0.0
  description: A simple service to encrypt strings using the Caesar cipher
paths:
  /encrypt:
    post:
      summary: Encrypt a string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                shift:
                  type: integer
                  minimum: 1
                  maximum: 25
              required:
                - text
                - shift
      responses:
        '200':
          description: Successful encryption
          content:
            application/json:
              schema:
                type: object
                properties:
                  encryptedText:
                    type: string
        '400':
          description: Invalid input